[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "sdimg"
version = "0.2.0"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "opencv-python-headless",
    "concave-hull",
]



[tool.setuptools.packages.find]
where = ["src"]
include = ["sdimg*"]

[tool.pytest.ini_options]
markers = []
